# Generated by Django 4.0.4 on 2022-05-15 17:31

from django.db import migrations, models
import recipes_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(help_text='Please enter a recipe name', max_length=150, verbose_name='Recipe Name')),
                ('recipe_food_group', models.CharField(choices=[('Beef', 'Beef'), ('Pork', 'Pork'), ('Lamb', 'Lamb'), ('Chicken', 'Chicken'), ('Fish', 'Fish'), ('Vegetable', 'Vegetable'), ('Soup', 'Soup'), ('Dessert', 'Dessert'), ('Cake', 'Cake'), ('Other', 'Other')], help_text='Please select the food group from the dropdown menu', max_length=50, verbose_name='Recipe Food Group')),
                ('recipe_ingredients', models.TextField(help_text='Please enter the ingredients and quantities to be used', max_length=5000, verbose_name='Recipe Ingredients')),
                ('recipe_instructions', models.TextField(help_text='Please enter the instructions for the recipe', max_length=25000, verbose_name='Recipe Instructions')),
                ('recipe_notes', models.TextField(blank=True, default='There are currently no notes associated with this recipe', help_text='Please enter any notes for the recipe', max_length=5000, verbose_name='Recipe Notes')),
                ('recipe_image', models.ImageField(blank=True, default='images/default.png', help_text='Please upload an image, a default image will be used if none selected', upload_to='images', validators=[recipes_app.models.validate_image], verbose_name='Recipe Image')),
                ('recipe_timestamp', models.DateTimeField(auto_now_add=True)),
                ('recipe_updated', models.DateTimeField(auto_now=True)),
                ('recipe_active', models.BooleanField(default=True)),
            ],
        ),
    ]
