# Generated by Django 4.0.4 on 2022-05-16 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0003_rename_user_recipe_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='author',
        ),
    ]
