# Generated by Django 4.0.4 on 2022-05-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0009_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
