# Generated by Django 4.0.4 on 2022-05-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0010_alter_recipe_recipe_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
