# Generated by Django 4.0.4 on 2022-05-18 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0012_alter_recipe_recipe_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_date_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
