# Generated by Django 4.0.4 on 2022-05-18 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0013_recipe_recipe_date_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_date_timestamp',
        ),
    ]
